# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', primary_key=True, auto_created=True)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.CharField(default=0, max_length=8)),
                ('email', models.EmailField(unique=True, default='', blank=True, max_length=255)),
                ('fechaNacimiento', models.DateTimeField(null=True, blank=True)),
                ('domicilio', models.CharField(default='', blank=True, max_length=254)),
                ('telefono', models.CharField(default='', blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('cuit', models.CharField(null=True, default=0, max_length=11)),
                ('nroUsuario', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('cambiar_cont', 'Puede cambiar su contrasena'), ('view_perfil_cliente', 'Puede ver su perfil de cliente'), ('view_facturas_cliente', 'Puede ver sus facturas')],
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ClienteLegado',
            fields=[
                ('numero', models.AutoField(serialize=False, db_column='NUMERO', primary_key=True)),
                ('nombre', models.CharField(db_column='NOMBRE', blank=True, max_length=254)),
                ('domicilio', models.CharField(db_column='DOMICILIO', blank=True, max_length=254)),
                ('localidad', models.CharField(db_column='LOCALIDAD', blank=True, max_length=11)),
                ('telefono', models.CharField(db_column='TELEFONO', blank=True, max_length=254)),
                ('condIva', models.CharField(db_column='COND_IVA', blank=True, max_length=18)),
                ('email', models.EmailField(null=True, unique=True, db_column='E_MAIL', blank=True, max_length=75)),
                ('tipoDoc', models.CharField(db_column='TIPO_DOC', blank=True, max_length=4)),
                ('nroDoc', models.CharField(db_column='NRO_DOC', blank=True, max_length=13)),
                ('fechaVtoCuit', models.DateTimeField(null=True, db_column='FECHAVTOCUIT', blank=True)),
                ('saldo', models.FloatField(null=True, db_column='SALDO', blank=True)),
                ('limiteCredito', models.FloatField(null=True, db_column='LIMITE_CREDITO', blank=True)),
                ('interesCredito', models.FloatField(null=True, db_column='INTERES_CREDITO', blank=True)),
                ('nroCuenta', models.CharField(db_column='NROCUENTA', blank=True, max_length=20)),
                ('bonificacion', models.FloatField(null=True, db_column='BONIFICACION', blank=True)),
                ('actividad', models.CharField(db_column='ACTIVIDAD', blank=True, max_length=20)),
                ('listaPrecio', models.CharField(db_column='LISTA_DE_PRECIO', blank=True, max_length=9)),
                ('compctacte', models.CharField(db_column='COMPCTACTE', blank=True, max_length=20)),
                ('formaPagoAsociada', models.SmallIntegerField(null=True, db_column='FORMAPAGOASOCIADA', blank=True)),
                ('aplicarRecargo', models.CharField(db_column='APLICAR_RECARGO', blank=True, max_length=1)),
                ('fechaAlta', models.DateTimeField(null=True, default='1930-1-1', db_column='FECHAALTA', blank=True)),
                ('idCodigoContable', models.FloatField(null=True, db_column='IDCODIGOCONTABLE', blank=True)),
                ('telefonoRefencia', models.CharField(db_column='TELEFONOREFENCIA', blank=True, max_length=20)),
                ('lugarTrabajo', models.CharField(db_column='LUGARTRABAJO', blank=True, max_length=30)),
                ('domicilioLaboral', models.CharField(db_column='DOMICILIOLABORAL', blank=True, max_length=30)),
                ('telefonoLaboral', models.CharField(db_column='TELEFONOLABORAL', blank=True, max_length=30)),
                ('fechaIngreso', models.DateTimeField(null=True, db_column='FECHAINGRESO', blank=True)),
                ('sueldo', models.FloatField(null=True, db_column='SUELDO', blank=True)),
                ('estadoCivil', models.CharField(db_column='ESTADOCIVIL', blank=True, max_length=1)),
                ('fechaNacimiento', models.DateTimeField(null=True, db_column='FECHANACIMIENTO', blank=True)),
                ('comentario', models.CharField(db_column='COMENTARIO', blank=True, max_length=999)),
                ('estado', models.CharField(db_column='ESTADO', blank=True, max_length=10)),
                ('idVendedor', models.IntegerField(null=True, db_column='IDVENDEDOR', blank=True)),
                ('idTipoPrecio', models.IntegerField(null=True, db_column='IDTIPOPRECIO', blank=True)),
                ('aplicarRetdgr', models.SmallIntegerField(null=True, db_column='APLICARRETDGR', blank=True)),
                ('idGrupo', models.IntegerField(null=True, db_column='IDGRUPO', blank=True)),
                ('marca', models.SmallIntegerField(null=True, db_column='MARCA', blank=True)),
                ('orden', models.IntegerField(null=True, db_column='ORDEN', blank=True)),
                ('telReferencia', models.IntegerField(null=True, db_column='TELREFERENCIA', blank=True)),
                ('cpLaboral', models.CharField(db_column='CP_LABORAL', blank=True, max_length=11)),
                ('legajo', models.CharField(db_column='LEGAJO', blank=True, max_length=19)),
                ('cargo', models.CharField(db_column='CARGO', blank=True, max_length=19)),
                ('categoria', models.CharField(db_column='CATEGORIA', blank=True, max_length=19)),
                ('idCalle', models.IntegerField(null=True, db_column='IDCALLE', blank=True)),
                ('altura', models.CharField(db_column='ALTURA', blank=True, max_length=29)),
                ('idBarrio', models.IntegerField(null=True, db_column='IDBARRIO', blank=True)),
                ('idEntre1', models.IntegerField(null=True, db_column='IDENTRE1', blank=True)),
                ('idEntre2', models.IntegerField(null=True, db_column='IDENTRE2', blank=True)),
                ('aplicarBonificacion', models.CharField(db_column='APLICARBONIFICACION', blank=True, max_length=1)),
                ('clientePreferencial', models.SmallIntegerField(null=True, db_column='CLIENTEPREFERENCIAL', blank=True)),
                ('codClientePreferencial', models.CharField(db_column='CODCLIENTEPREFERENCIAL', blank=True, max_length=20)),
                ('puntosAcumulados', models.IntegerField(null=True, db_column='PUNTOSACUMULADOS', blank=True)),
                ('recargos', models.FloatField(null=True, db_column='RECARGOS', blank=True)),
                ('situacion', models.SmallIntegerField(null=True, db_column='SITUACION', blank=True)),
                ('idClasificacion', models.IntegerField(null=True, db_column='IDCLASIFICACION', blank=True)),
                ('aplicarCostoOperativo', models.SmallIntegerField(null=True, db_column='APLICARCOSTOOPERATIVO', blank=True)),
                ('puestoId', models.CharField(db_column='PUESTO_ID', blank=True, max_length=30)),
                ('usuarioId', models.CharField(db_column='USUARIO_ID', blank=True, max_length=20)),
                ('fechaUpdate', models.DateTimeField(null=True, db_column='FECHA_UPDATE', blank=True)),
                ('noAplicarPromociones', models.SmallIntegerField(null=True, db_column='NOAPLICARPROMOCIONES', blank=True)),
                ('diasVencimientoCuentaCorriente', models.SmallIntegerField(null=True, db_column='DIASVENCIMIENTOCUENTACORRIENTE', blank=True)),
                ('restringirVentaConSaldosPendientes', models.SmallIntegerField(null=True, db_column='RESTRINGIRVENTACONSALDOSPENDIENTES', blank=True)),
                ('userDef_0', models.CharField(null=True, db_column='UserDef_0', blank=True, max_length=20)),
                ('userDef_1', models.CharField(null=True, db_column='UserDef_1', blank=True, max_length=20)),
                ('userDef_2', models.CharField(null=True, db_column='UserDef_2', blank=True, max_length=20)),
                ('userDef_3', models.CharField(null=True, db_column='UserDef_3', blank=True, max_length=20)),
                ('userDef_4', models.CharField(null=True, db_column='UserDef_4', blank=True, max_length=20)),
                ('userDef_5', models.CharField(null=True, db_column='UserDef_5', blank=True, max_length=20)),
                ('idcobrador', models.IntegerField(null=True, db_column='IDCobrador', blank=True)),
            ],
            options={
                'db_table': 'FACT0004',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', primary_key=True, auto_created=True)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.CharField(default=0, max_length=8)),
                ('email', models.EmailField(unique=True, default='', blank=True, max_length=255)),
                ('fechaNacimiento', models.DateTimeField(null=True, blank=True)),
                ('domicilio', models.CharField(default='', blank=True, max_length=254)),
                ('telefono', models.CharField(default='', blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('nroUsuario', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('cambiar_cont', 'Puede cambiar su contrasena'), ('view_facturas', 'Puede ver las facutras de los clientes'), ('view_lista_cliente', 'Puede ver la lista de clientes'), ('view_detalle_cliente', 'Puede ver detalle cliente'), ('update_cliente', 'Puede modificar cliente'), ('agregar_cliente', 'Puede agregar cliente'), ('del_cliente', 'Puede eliminar cliente'), ('view_perfil_empleado', 'Puede ver su perfil de empleado')],
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', primary_key=True, auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('slug', models.SlugField(unique=True, max_length=200)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'db_table': 'Entradas',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Historiales',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', primary_key=True, auto_created=True)),
                ('nroUsuario', models.CharField(max_length=200)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(blank=True, max_length=200)),
                ('perfil', models.CharField(blank=True, max_length=20)),
                ('autenticado', models.CharField(blank=True, max_length=10)),
                ('ip', models.IPAddressField(blank=True)),
            ],
            options={
                'db_table': 'Historiales',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', primary_key=True, auto_created=True)),
                ('slug', models.SlugField(unique=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'Tags',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(to='FacturasNorte.Tag'),
            preserve_default=True,
        ),
    ]
