# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacturasNorte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=8, default=0)),
                ('username', models.EmailField(max_length=255, unique=True, blank=True, default='')),
                ('fechaNacimiento', models.DateTimeField(null=True, blank=True)),
                ('domicilio', models.CharField(max_length=254, blank=True, default='')),
                ('telefono', models.CharField(max_length=254, blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('cuit', models.CharField(max_length=11, null=True, default=0)),
                ('nroUsuario', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('cambiar_cont', 'Puede cambiar su contrasena'), ('view_perfil_cliente', 'Puede ver su perfil de cliente'), ('view_facturas_cliente', 'Puede ver sus facturas')],
                'db_table': 'Clientes',
                'verbose_name_plural': 'Clientes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ClienteLegado',
            fields=[
                ('numero', models.AutoField(db_column='NUMERO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=254, blank=True)),
                ('domicilio', models.CharField(db_column='DOMICILIO', max_length=254, blank=True)),
                ('localidad', models.CharField(db_column='LOCALIDAD', max_length=11, blank=True)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=254, blank=True)),
                ('condIva', models.CharField(db_column='COND_IVA', max_length=18, blank=True)),
                ('username', models.EmailField(db_column='E_MAIL', max_length=75, unique=True, blank=True, null=True)),
                ('tipoDoc', models.CharField(db_column='TIPO_DOC', max_length=4, blank=True)),
                ('nroDoc', models.CharField(db_column='NRO_DOC', max_length=13, blank=True)),
                ('fechaVtoCuit', models.DateTimeField(db_column='FECHAVTOCUIT', null=True, blank=True)),
                ('saldo', models.FloatField(db_column='SALDO', null=True, blank=True)),
                ('limiteCredito', models.FloatField(db_column='LIMITE_CREDITO', null=True, blank=True)),
                ('interesCredito', models.FloatField(db_column='INTERES_CREDITO', null=True, blank=True)),
                ('nroCuenta', models.CharField(db_column='NROCUENTA', max_length=20, blank=True)),
                ('bonificacion', models.FloatField(db_column='BONIFICACION', null=True, blank=True)),
                ('actividad', models.CharField(db_column='ACTIVIDAD', max_length=20, blank=True)),
                ('listaPrecio', models.CharField(db_column='LISTA_DE_PRECIO', max_length=9, blank=True)),
                ('compctacte', models.CharField(db_column='COMPCTACTE', max_length=20, blank=True)),
                ('formaPagoAsociada', models.SmallIntegerField(db_column='FORMAPAGOASOCIADA', null=True, blank=True)),
                ('aplicarRecargo', models.CharField(db_column='APLICAR_RECARGO', max_length=1, blank=True)),
                ('fechaAlta', models.DateTimeField(db_column='FECHAALTA', null=True, blank=True, default='1930-1-1')),
                ('idCodigoContable', models.FloatField(db_column='IDCODIGOCONTABLE', null=True, blank=True)),
                ('telefonoRefencia', models.CharField(db_column='TELEFONOREFENCIA', max_length=20, blank=True)),
                ('lugarTrabajo', models.CharField(db_column='LUGARTRABAJO', max_length=30, blank=True)),
                ('domicilioLaboral', models.CharField(db_column='DOMICILIOLABORAL', max_length=30, blank=True)),
                ('telefonoLaboral', models.CharField(db_column='TELEFONOLABORAL', max_length=30, blank=True)),
                ('fechaIngreso', models.DateTimeField(db_column='FECHAINGRESO', null=True, blank=True)),
                ('sueldo', models.FloatField(db_column='SUELDO', null=True, blank=True)),
                ('estadoCivil', models.CharField(db_column='ESTADOCIVIL', max_length=1, blank=True)),
                ('fechaNacimiento', models.DateTimeField(db_column='FECHANACIMIENTO', null=True, blank=True)),
                ('comentario', models.CharField(db_column='COMENTARIO', max_length=999, blank=True)),
                ('estado', models.CharField(db_column='ESTADO', max_length=10, blank=True)),
                ('idVendedor', models.IntegerField(db_column='IDVENDEDOR', null=True, blank=True)),
                ('idTipoPrecio', models.IntegerField(db_column='IDTIPOPRECIO', null=True, blank=True)),
                ('aplicarRetdgr', models.SmallIntegerField(db_column='APLICARRETDGR', null=True, blank=True)),
                ('idGrupo', models.IntegerField(db_column='IDGRUPO', null=True, blank=True)),
                ('marca', models.SmallIntegerField(db_column='MARCA', null=True, blank=True)),
                ('orden', models.IntegerField(db_column='ORDEN', null=True, blank=True)),
                ('telReferencia', models.IntegerField(db_column='TELREFERENCIA', null=True, blank=True)),
                ('cpLaboral', models.CharField(db_column='CP_LABORAL', max_length=11, blank=True)),
                ('legajo', models.CharField(db_column='LEGAJO', max_length=19, blank=True)),
                ('cargo', models.CharField(db_column='CARGO', max_length=19, blank=True)),
                ('categoria', models.CharField(db_column='CATEGORIA', max_length=19, blank=True)),
                ('idCalle', models.IntegerField(db_column='IDCALLE', null=True, blank=True)),
                ('altura', models.CharField(db_column='ALTURA', max_length=29, blank=True)),
                ('idBarrio', models.IntegerField(db_column='IDBARRIO', null=True, blank=True)),
                ('idEntre1', models.IntegerField(db_column='IDENTRE1', null=True, blank=True)),
                ('idEntre2', models.IntegerField(db_column='IDENTRE2', null=True, blank=True)),
                ('aplicarBonificacion', models.CharField(db_column='APLICARBONIFICACION', max_length=1, blank=True)),
                ('clientePreferencial', models.SmallIntegerField(db_column='CLIENTEPREFERENCIAL', null=True, blank=True)),
                ('codClientePreferencial', models.CharField(db_column='CODCLIENTEPREFERENCIAL', max_length=20, blank=True)),
                ('puntosAcumulados', models.IntegerField(db_column='PUNTOSACUMULADOS', null=True, blank=True)),
                ('recargos', models.FloatField(db_column='RECARGOS', null=True, blank=True)),
                ('situacion', models.SmallIntegerField(db_column='SITUACION', null=True, blank=True)),
                ('idClasificacion', models.IntegerField(db_column='IDCLASIFICACION', null=True, blank=True)),
                ('aplicarCostoOperativo', models.SmallIntegerField(db_column='APLICARCOSTOOPERATIVO', null=True, blank=True)),
                ('puestoId', models.CharField(db_column='PUESTO_ID', max_length=30, blank=True)),
                ('usuarioId', models.CharField(db_column='USUARIO_ID', max_length=20, blank=True)),
                ('fechaUpdate', models.DateTimeField(db_column='FECHA_UPDATE', null=True, blank=True)),
                ('noAplicarPromociones', models.SmallIntegerField(db_column='NOAPLICARPROMOCIONES', null=True, blank=True)),
                ('diasVencimientoCuentaCorriente', models.SmallIntegerField(db_column='DIASVENCIMIENTOCUENTACORRIENTE', null=True, blank=True)),
                ('restringirVentaConSaldosPendientes', models.SmallIntegerField(db_column='RESTRINGIRVENTACONSALDOSPENDIENTES', null=True, blank=True)),
                ('userDef_0', models.CharField(db_column='UserDef_0', max_length=20, null=True, blank=True)),
                ('userDef_1', models.CharField(db_column='UserDef_1', max_length=20, null=True, blank=True)),
                ('userDef_2', models.CharField(db_column='UserDef_2', max_length=20, null=True, blank=True)),
                ('userDef_3', models.CharField(db_column='UserDef_3', max_length=20, null=True, blank=True)),
                ('userDef_4', models.CharField(db_column='UserDef_4', max_length=20, null=True, blank=True)),
                ('userDef_5', models.CharField(db_column='UserDef_5', max_length=20, null=True, blank=True)),
                ('idcobrador', models.IntegerField(db_column='IDCobrador', null=True, blank=True)),
            ],
            options={
                'db_table': 'FACT0004',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=8, default=0)),
                ('username', models.EmailField(max_length=255, unique=True, blank=True, default='')),
                ('fechaNacimiento', models.DateTimeField(null=True, blank=True)),
                ('domicilio', models.CharField(max_length=254, blank=True, default='')),
                ('telefono', models.CharField(max_length=254, blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('nroUsuario', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('cambiar_cont', 'Puede cambiar su contrasena'), ('view_facturas', 'Puede ver las facutras de los clientes'), ('view_lista_cliente', 'Puede ver la lista de clientes'), ('view_detalle_cliente', 'Puede ver detalle cliente'), ('update_cliente', 'Puede modificar cliente'), ('agregar_cliente', 'Puede agregar cliente'), ('del_cliente', 'Puede eliminar cliente'), ('view_perfil_empleado', 'Puede ver su perfil de empleado')],
                'db_table': 'Empleados',
                'verbose_name_plural': 'Empleados',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Novedad',
                'db_table': 'Entradas',
                'verbose_name_plural': 'Novedades',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Historiales',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('nroUsuario', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200, blank=True)),
                ('fecha', models.DateTimeField(max_length=200, blank=True)),
                ('perfil', models.CharField(max_length=20, blank=True)),
                ('autenticado', models.CharField(max_length=10, blank=True)),
                ('ip', models.IPAddressField(blank=True)),
            ],
            options={
                'verbose_name': 'Historial',
                'db_table': 'Historiales',
                'verbose_name_plural': 'Historial de sesiones',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Historiales_registros',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('cuit_cli', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200, blank=True)),
                ('fecha', models.DateTimeField(max_length=200, blank=True)),
                ('operador', models.CharField(max_length=20, blank=True)),
                ('accion', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'verbose_name': 'Historiales_registros',
                'db_table': 'Historiales_registros',
                'verbose_name_plural': 'Historial de Registro de Usuarios',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'db_table': 'Tags',
                'verbose_name_plural': 'Tags',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(to='FacturasNorte.Tag'),
            preserve_default=True,
        ),
        migrations.AlterModelOptions(
            name='historialcontrasena',
            options={'verbose_name': 'Cambio de contraseña', 'verbose_name_plural': 'Historial de Cambios de contraseña'},
        ),
    ]
