PDF_ROOT = '//maria/FacturacionPDF/'
CARPETA_DIARIOS = 'C:/Diarios/'
CARPETA_DIARIOS2 = 'C:/Diarios2'
CARPETA_FACTURAS = 'FacturasPDF/'
CARPETA_PEDIDOS = 'PrefacturasPDF/'
PDF_FACTURAS = PDF_ROOT + CARPETA_FACTURAS
PDF_PEDIDOS = PDF_ROOT + CARPETA_PEDIDOS
EMAIL_ENTRADA = 'serviciosnorte2@gmail.com'
EMAIL_SALIDA = 'serviciosnorte2@gmail.com'
