PDF_ROOT = 'C:/Apache24/htdocs/PDFs/'
PDF_FACTURAS = PDF_ROOT + 'facturas/' 
PDF_PEDIDOS = PDF_ROOT + 'pedidos/' 
EMAIL_ENTRADA = 'julian_rd7@hotmail.com'
EMAIL_SALIDA = 'julian.rd7@gmail.com'
PDF_DIARIO = PDF_ROOT + 'diario/Diario_del_dia.pdf'